#DEV evironment 

app:
  message: message:This is the property file fo the ${spring.application.name} for DEV 

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:nem:db;DB_CLOSE_DELAY=-1
    username: sa
    password: sa